import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Provider } from 'react-wrap-balancer'
import AppProvider from '@/provider/app-provider'
import { Toaster } from '@/components/ui/toaster'
import TopLoader from '@/components/top-loader'
import { ThemeProvider } from '@/provider/theme-provider'
import { ScrollProgress } from '@/components/ui/scroll-progress'
import { AOSInit } from '@/components/aos'
import { UserProvider } from '@/contexts/profile-context'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Task Zen',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <AppProvider>
            <ThemeProvider attribute='class' defaultTheme='light' forcedTheme='light'>
              <UserProvider>
                <TopLoader />
                <AOSInit />
                <ScrollProgress />
                {children}
                <Toaster />
              </UserProvider>
            </ThemeProvider>
          </AppProvider>
        </Provider>
      </body>
    </html>
  )
}
